### ISSUE TITLE
Design demos for event websites

### ISSUE THREAD

**Issue by chaixinzhe2000** [FullStackAtBrownTeam/project-brown-space-horizons#3]
Please put 3 webpages for events here before the next meeting, and explain why you like it.

**Comment by itsthemoon** [comment]
1. https://preview.themeforest.net/item/the-keynote-conference-event-meeting-wordpress-theme/full_screen_preview/9718856?_ga=2.174528935.403295314.1609169939-1158905421.1609169515

  *I like how the homepage displays a countdown until the event date, and I like the slides of speakers. I feel like having both of those on the homepage might draw someone in who just lands on the website. *

2. http://conference-template.webflow.io/schedule 
*I like how on the schedule page, there is different sections for different days. If we could add this to our schedule I think it might make the page look much cleaner. 

3. http://meetup-template.webflow.io/about
*I like the way this webpage displays its sponsors. I don't know if we need a whole page dedicated to sponsors, and this website has its sponsors on its about page, which we could probably do as well. *

**Comment by lrandall521** [comment]
https://demo.themewinter.com/html/exhibz/classic/schedule.html
 - This site has the different speakers for each day page (like #2 Jackson found)
 - I also like the footer they have on every page with links and a mini contact form

https://demo.web3canvas.com/themeforest/gather/index.html
 - We could use some similar animations on ours, when users first go on the page. This one has a bit much but I think some animated text sections would look good

http://confix.themerex.net/event/international-conference-on-green-energy/
 - The animations on this are also cool
 - I like how the header buttons turn a different color when you click them (in general this site has nice buttons too)

**Comment by schornb** [comment]
https://jevelin.shufflehound.com/startup-clean/
- I like how it has the links to the social media pages need the top right with other links in the website (potentially where we can put the registration information)
- I like the ability to scroll through different reviews; we could potentially use it to show all the speakers and the sponsors

http://demo.themewinter.com/wp/exhibz/home-2/
- We could have a timer until the actual event on the top of the page
- The animation where the numbers increase could be a cool way of showing when the event is going to be (or perhaps use the same animation to show "Space Horizons 2021" in the first page)

https://radiustheme.com/demo/wordpress/eventalk/
-I like how it displays the times and links to each of the events at the conference. It seems simple to implement and could clearly shows when certain events are during Space Horizons 2021
-The opening page showing the event transitions through different pictures showing off different aspects of the events seamlessly. They are neat animations we can consider as we are making the site.

**Comment by chaixinzhe2000** [comment]
Everyone has done a great job! Closing the issue now.
