### ISSUE TITLE
Good Design Language in Website Demos

### ISSUE THREAD

**Issue by chaixinzhe2000** [FullStackAtBrownTeam/project-brown-space-horizons#4]
### Action Item
Similar to last time, I want everyone to find **3 websites** with good design language and provide a short explanation for each one. 
**Deadline: Before Saturday Meetting**

### What do I mean by "design language"?
A real "design language" is usually a set of stylistic guideline that is published by companies, such as:

[Human Interface Guideline by Apple](https://developer.apple.com/design/human-interface-guidelines/)
[Fluent Design by Microsoft](https://www.microsoft.com/design/fluent/#/)

However, we are making websites, and we don't have enough time to develop a full design language. Therefore, what we want to do is to find some good websites, and learn from their designs. 

### Example
_[Github Universe](https://githubuniverse.com/)_
_I love Github Universe's box design for displaying events. Maybe we can also incorporate it into our own website. Also, neon light is really a good color scheme for dark websites._

### How to find a good website for the task?
One way is to find a big company's annual conference page. Of course, make sure their design fit our need (we don't need crazy animation transition that Apple might have).

**Good luck, and looking forward to your reply!**

**Comment by lrandall521** [comment]
https://aas.org/
I like the little orbit animations around the professions they have. Maybe randomly select some speakers to feature and do that? Also at the bottom of the page they have a cool "back to top".

https://ecospears.com/
There are many cool effects on this webpage, like the background animations and the keywords cycling through. I'm not sure if a video is too distracting but it might be worth looking into.

https://www.demconvention.com/
I like how the images kind of sweep in like puzzle pieces. Also I enjoy the buttons which have an underline filling when you hover over them.

**Comment by itsthemoon** [comment]
https://www.brown.edu/
As cliché as it may sound I like the brown website. I especially like the animation that appears when you hover over news and events. We could use that same animation for speakers or anything that is put into a box like that (ex. speakers on the home page). 

https://www.oasen.nl/drinkwater
I have never seen anything like this before, but the animation that comes when you change pages is nice. We could possibly have it not with water, but maybe shooting stars or something space related. 

https://marchermarkholt.com/en/
I like how sections pop up as you scroll down the page. The might look cool to have on the home page.

**Comment by schornb** [comment]
https://www.squarespace.com/
Similar to our discussion last week, if you put your mouse near a link, an animation will perform to remove the line under the text. It's a neat animation and it tells the reader that a link is there (could be good in the event speakers section especially)

https://www.sony.com/
Something I like about this website's design is that 1) it seamlessly transitions between parts of the website and 2) when you hover over an image, it darkens and sometimes give access to more information like social media or a specific link.

https://wonderfulweekends.withgoogle.com/play
Perhaps a little too complex, but it would be cool if could you perhaps move objects in the background (maybe moving around stars or even could be a new way to represent a gallery by scrolling through images in "space")

**Comment by chaixinzhe2000** [comment]
good job everyone
